dist: trusty
language: php

env:
 - CODECOV_TOKEN="86760c0b-d0b1-4f5d-be3f-d7b4fac9c9c3"

php:
 - 7.4

sudo: false

install:
 - travis_retry composer install --no-interaction --prefer-source

script:
 - vendor/bin/phpunit --verbose

after_success:
 - bash <(curl -s https://codecov.io/bash)
